name: "Add milestoned issues to tracker"
on:
  issues:
    types: [milestoned]

jobs:
  add-milestoned-issues-to-tracker:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.issue.milestone.title }}
