name: "Add incident issues to tracker"
on:
  issues:
    types: [opened]

jobs:
  add-rootly-postmortems-to-tracker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@main
      if: ${{ github.event_name == 'issues' && contains(github.event.issue.body, 'created-by-rootly') }}
      with:
        project-url: https://github.com/orgs/cadedaniel-org/projects/1/
        github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
    - name: "Create a new milestone"
      uses: oinume/create-scheduled-milestone-action@v1.0.0
      with:
        title: "${{ github.event.issue.title }}"
        state: "open"
        description: "Milestone for action items of [${{ github.event.issue.title}}](${{ github.event.issue.html_url }})."
        #due_on: "${{ steps.set-due-on.outputs.due_on }}"
      env:
        GITHUB_TOKEN: "${{ secrets.ADD_TO_PROJECT_PAT }}"


# This can't handle titles with spaces or colons.
#    - name: Create new milestone
#      if: ${{ github.event_name == 'issues' && contains(github.event.issue.body, 'created-by-rootly') }}
#      uses: WyriHaximus/github-action-create-milestone@v1
#      with:
#        title: '${{ github.event.issue.title }}'
#      env:
#        GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        
        
#    - uses: github/issue-labeler@v2.4.1
#      if: ${{ github.event_name == 'issues' && contains(github.event.issue.body, 'created-by-rootly') }}
#      with:
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#        configuration-path: .github/labeler.yml
#        enable-versioned-regex: 0
