name: Add incidents to incident project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cadedaniel/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: rootly-postmortem
          label-operator: OR
