name: "(on comment) Add incident issues to tracker"

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  check_has_command_text:
    runs-on: ubuntu-latest
    outputs:
      comment_has_command_text: ${{ steps.check_comment_has_command_text.outputs.comment_has_command_text }}
      body_has_command_text: ${{ steps.check_body_has_command_text.outputs.body_has_command_text }}
    steps:
      - id: check_comment_has_command_text
        run: echo "::set-output name=comment_has_command_text::${{ !github.event.issue.pull_request && github.event.comment.body == '/created-by-rootly' }}"
      - id: check_body_has_command_text
        run: echo "::set-output name=body_has_command_text::${{ github.event_name == 'issues' && contains(github.event.issue.body, '/created-by-rootly') }}"
  add_command_as_comment:
    runs-on: ubuntu-latest
    needs: check_has_command_text
    if: needs.check_has_command_text.outputs.body_has_command_text == 'true'
    steps:
      - name: "Add command comment."
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/created-by-rootly'
            });
  add_to_project:
    runs-on: ubuntu-latest
    needs: check_has_command_text
    if: needs.check_has_command_text.outputs.comment_has_command_text == 'true'
    steps:
      - name: "Add issue to postmortem tracker"
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/cadedaniel-org/projects/1/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      - name: "Add label to PM issue, create PM action item milestone, add comment to issue."
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pi-postmortem']
            })

            pm_issue = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            const max_milestone_length = 200
            const issue_title = pm_issue.data.title.substr(0, max_milestone_length)
            milestone = await github.rest.issues.createMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue_title + " [postmortem-tracker]",
              description: "Milestone for action items of postmortem [" + issue_title + "](" + pm_issue.data.html_url + ")."
            });

            const command_tag = '`/created-by-rootly`'
            const label = '`pi-postmortem`'
            const comment_string = `[bot] I see a ${command_tag}. I've done the following things:
              * Added this issue to the [postmortem tracker](https://github.com/orgs/cadedaniel-org/projects/1/views/10).
              * Created [a milestone for action items](https://github.com/cadedaniel-org/issues/milestone/${milestone.data.number}).
              * Added the label [${label}](https://github.com/cadedaniel-org/issues/labels/pi-postmortem) to this issue.`

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_string
            });
